### PR TITLE
Post fixes

### PR DESCRIPTION
**Pull request by VulpoTheDev**
**What I did:**

- I have some issues with how the post looks
- Fixed Padding

Before: 
image

After:
image

- Centered the "Welcome Back" text in the index page since it looked really nice
- Fixed Spacing Issue with the Buttons

Before:
image

After:
image

- Added Placeholder to search bar to more context of the input despite there being an magnify glass
image

- Improved Accessbility
image

- Added 3 Dotted Button when hovering
image

**Overall**

Before:

image

After: 
image

- [x] Applied `npm run format`
- [x] Tested the changes locally

### CODE REVIEW

**Comment by Alekuso** [comment]
There's no fox in your PR, banned

**Comment by VulpoTheDev** [comment]
image
Fox :3

**Comment by Alekuso** [comment]
Now marry me

**Comment by VulpoTheDev** [comment]
:flushed:

**Review by Alekuso — DISMISSED** [review]
LGTM

**Review by Alekuso — APPROVED** [review]

**Pull request merged**
