### PR TITLE
Profile

### PR DESCRIPTION
**Pull request by Alekuso**
**What I did:**
Implement the profile page

**Related Issues**
/

**Optionally: Add additional Things to this PR, or a picture of a furry animal :3**

- [X] Applied `npm run format`
- [X] Tested the changes locally

### CODE REVIEW

**Comment by Alekuso** [comment]
It looks like that the mobile view of the profile has gotten really weird for not much reason, probably because of cache or idk, will try to fix that

**Comment by Alekuso** [comment]
So the interaction field width depends of the aboutMe span, basically if the description is empty, the interaction field has no width, and is large when the aboutMe fills the entire screen

**Review by FissionFeline — DISMISSED** [review]
Good work soldier

**Review by VulpoTheDev — APPROVED** [review]
Looks good to me!

**Pull request merged**
