### PR TITLE
Alekuso header

### PR DESCRIPTION
**Pull request by Alekuso**
**What I did:**

I added features to the header

**Related Issues**

/

**Optionally: Add additional Things to this PR, or a picture of a furry animal :3**

**TODO**

Fix the issues related to that
**Finish the header before merging.**

- [X] Applied `npm run format`
- [X] Tested the changes locally

### CODE REVIEW

**Review by FissionFeline — DISMISSED** [review]
Looks good

**Review by staxfur — DISMISSED** [review]
Gonna steal all your food :P

**Comment by staxfur** [comment]
Seems like you created a variable in your code and never used it.

**Comment by Alekuso** [comment]
> Gonna steal all your food :P

I think that's the WelcomeBack component, which is no longer used, for now, I'm trying to finish the header first before re-implementing it

**Comment by staxfur** [comment]
Sure! One thing at a time ^^

**Review by FissionFeline — APPROVED** [review]
Im proud of you son

**Pull request merged**
